# --- FUENTE ---

font_family      Lilex Medium
bold_font        Lilex Bold
italic_font      Lilex Light Italic
bold_italic_font Lilex Bold Italic

font_size 15.5

adjust_line_height 130%

# --- TEMA DE COLORES (Gruvbox Material Dark) ---
background #151515

foreground #fbf1c7
cursor #d4be98
cursor_text_color background
selection_foreground  #d4be98
selection_background  #3c4038
active_border_color   #a9b665
inactive_border_color #1d2021
color0 #867970
color8 #867970
color1 #d67b76
color9 #d67b76
color2 #a3ae6d
color10 #a3ae6d
color3 #cba364
color11 #cba364
color4 #82a9a0
color12 #82a9a0
color5 #cb8e9e
color13 #cb8e9e
color6 #8daf87
color14 #8daf87
color7 #d7c5a7
color15 #d7c5a7

# --- APARIENCIA Y DISEÑO MINIMALISTA ---

background_opacity 1.0
background_blur 0

window_padding_width 15
window_padding 20

hide_window_decorations yes

window_border_width 0

cursor_shape block
cursor_blink_interval 0
repaint_delay 10
input_delay 3
sync_to_monitor yes

scrollback_lines 2000

copy_on_select yes

enable_audio_bell no

confirm_os_window_close 0
