[module/sep]
type = custom/text
content = " | "
content-foreground = ${colors.disabled}

[module/i3]
type = internal/i3
format = <label-state>
index-sort = true
enable-click = true

; Workspace activo: Fondo VERDE (primary), Texto del fondo (background)
label-focused = %index%
label-focused-foreground = ${colors.background}
label-focused-background = #d7c5a7
label-focused-padding = 1
label-focused-font = 2

label-unfocused = %index%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

label-urgent = %index%
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1

label-visible = %index%
label-visible-padding = 1

[module/network]
type = internal/network
interface = wlan0
interval = 3.0

; CONECTADO: Solo el nombre de la red, sin prefijos ni iconos extra
format-connected = <label-connected>
label-connected = %essid%
label-connected-foreground = ${colors.foreground}

; DESCONECTADO: Mensaje sad personalizado
format-disconnected = <label-disconnected>
label-disconnected = "wifi 404 :("
label-disconnected-foreground = ${colors.alert}

[module/battery]
type = internal/battery
full-at = 80
battery = BAT0
adapter = AC
poll-interval = 2

; --- LOGICA TEXTUAL SIN ICONOS ---

; Cargando: "54% >" (En color verde/primary)
format-charging = <label-charging>
label-charging = %percentage% >
label-charging-foreground = ${colors.primary}

; Descargando: "54% <" (En color normal, indicando consumo)
format-discharging = <label-discharging>
label-discharging = %percentage% <
label-discharging-foreground = ${colors.alert}

; Llena: "100% =" (En color verde)
format-full = <label-full>
label-full = 80 =
label-full-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1
date = "%a %{F#82a9a0}%d%{F-} %H:%M"
label = %date%
label-foreground = ${colors.foreground}

[module/volume]
type = internal/pulseaudio

; Eliminamos <ramp-volume>, solo dejamos la etiqueta
format-volume = <label-volume>

; Formato: "50% Δ"
label-volume = %percentage% Δ
label-volume-foreground = #cba364

; Formato cuando está en silencio: "muted"
label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/bluetooth-battery]
type = custom/script
exec = ~/.config/polybar/scripts/headphones_battery_status.sh
interval = 50

; --- COLOR PASTEL ELEGIDO ---
format-foreground = #a8a1be

format = <label>
label = %output%
