[colors]
background = #0D0D0D
; background = #001524
background-alt = #1A1A1A
window-bg = #0A0A0A
foreground = #E0E0E0
foreground-alt = #BFBAAA
primary = #C391E6
secondary = #BD93F9
alert = #FCA5A5
highlight = #FFFFFF
green = #50FA7B
yellow = #FFB86C
blue = #0369A1
orange = #F59E0B

[bar/main]
width = 100%
height = 28pt
offset-x = 0
offset-y = 0
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 2
line-color = ${colors.primary}
border-size = 0
border-color = #00000000
padding-left = 3
padding-right = 3
module-margin-left = 2
module-margin-right = 2
font-0 = "CozetteCrossedSevenVector:size=16;2"
modules-left = i3 xwindow
modules-center = date
modules-right = network battery pulseaudio

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
label-mode-padding = 2
label-mode-foreground = ${colors.primary}
label-mode-background = ${colors.background}
label-focused = %index% <-
label-focused-background = ${colors.window-bg}  # Fondo más oscuro para la ventana activa
label-focused-underline = ${colors.primary}
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-padding = 2
label-visible = %index%
label-visible-padding = 2
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
label = <- %title:0:30:...% <-
label-background = ${colors.background}
label-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 1
date = %a %d %b
time = %H:%M
label = -> %date% %time% <-
label-background = ${colors.background}
label-foreground = ${colors.foreground}


[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume> <bar-volume>
label-volume = -> %percentage%%
label-volume-background = ${colors.background}
label-volume-foreground = ${colors.foreground}
label-muted = -> muted
label-muted-background = ${colors.background}
label-muted-foreground = ${colors.alert}
bar-volume-width = 10
bar-volume-foreground-0 = ${colors.secondary}
bar-volume-foreground-1 = ${colors.secondary}
bar-volume-foreground-2 = ${colors.secondary}
bar-volume-foreground-3 = ${colors.secondary}
bar-volume-foreground-4 = ${colors.secondary}
bar-volume-foreground-5 = ${colors.secondary}
bar-volume-foreground-6 = ${colors.primary}
bar-volume-foreground-7 = ${colors.primary}
bar-volume-foreground-8 = ${colors.alert}
bar-volume-foreground-9 = ${colors.alert}
bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-fill = -
bar-volume-empty = -
bar-volume-empty-foreground = ${colors.foreground}50

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 99
format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
label-charging = -> Charging: %percentage%%
label-discharging = -> Battery: %percentage%%
label-full = -> Full: %percentage%%
label-charging-background = ${colors.background}
label-charging-foreground = ${colors.foreground}
label-discharging-background = ${colors.background}
label-discharging-foreground = ${colors.foreground}
label-full-background = ${colors.background}
label-full-foreground = ${colors.foreground}

[module/network]
type = internal/network
interface = wlan0
interval = 2
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = -> %essid%
label-disconnected = -> No wifi :c
label-connected-background = ${colors.background}
label-connected-foreground = ${colors.foreground}
label-disconnected-background = ${colors.background}
label-disconnected-foreground = ${colors.alert}
