[colors]
background = #FFEBD4
foreground = #754E1A
secondary = #8D6E63

[bar/main]
background = ${colors.background}
foreground = ${colors.foreground}
height = 23pt
; font-0 = "Iosevka Nerd Font:size=16;2"
font-0 = "JetBrainsMonoNL NFP Light:size=15;2"
font-1 = "Font Awesome 6 Free:style=Solid:size=12;2"
modules-left = xworkspaces
modules-center = date
modules-right = battery pulseaudio network flameshot
border-size = 0
radius = 0
padding-left = 2
padding-right = 2
module-margin = 1
separator = |

width = 85%
offset-x = 7.5%
offset-y = 30  

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = #BF9264 
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = #BBD8A3 
label-urgent-padding = 1

label-empty =
label-empty-padding = 0
; type = internal/xworkspaces
; label-active = | %index% |
; label-occupied = | %index% |
; label-empty = 
; label-empty-padding = 0
; label-only-focused-monitor = true
; label-active-foreground = #A79277
; label-active-background = #D1BB9E 
; label-occupied-foreground = #A79277
; label-occupied-background = #EAD8C0

[module/date]
type = internal/date
interval = 1
date = %a, %d %B at %I:%M %p  
label = %date%

[module/battery]
type = internal/battery
battery = BAT0
format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
format-charging-prefix = "⚡ "  
format-discharging-prefix = "🔋 "  
format-full-prefix = "🔋 "  

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume = 🔊 %percentage%%  
format-muted =  shh 
label-muted =  shh 

[module/network]
type = internal/network
interface = wlan0 
format-connected = <label-connected>
label-connected = 🌐 %essid%  
format-disconnected = 🌐 No wifi u.u

[module/flameshot]
type = custom/script
exec = echo "Screenshot"
click-left = flameshot gui &
label =  Pic
label-background = ${colors.background}
label-foreground = ${colors.foreground}
